export const SET_ENTITIES = "SET_ENTITIES";
export const SET_RECIPES = "SET_RECIPES";
export const SET_TABS = "SET_TABS";
export const SET_SELECTED_ENTITY = "SET_SELECTED_ENTITY";

export const FETCH_RECIPES = "FETCH_RECIPES";