export const SET_ENTITIES = "SET_ENTITIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_GAME_TYPES = "SET_GAME_TYPES";
export const SET_RECIPES = "SET_RECIPES";
export const SET_TABS = "SET_TABS";
export const SET_SELECTED_ENTITY = "SET_SELECTED_ENTITY";
export const SET_LOADING = "SET_LOADING";
export const SET_LOADED_COMPONENTS = "SET_LOADED_COMPONENTS";
export const SET_ENTITIES_JSON = "SET_ENTITIES_JSON";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_PER_SECOND = "SET_PER_SECOND";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_GAME_TYPES = "FETCH_GAME_TYPES";
export const FETCH_ENTITIES = "FETCH_ENTITIES";
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";

export const SEND_CATEGORIES_TYPES = "SEND_CATEGORIES_TYPES";
export const CREATE_ENTITIES = "CREATE_ENTITIES";
export const CREATE_RECIPES = "CREATE_RECIPES";

